/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HADI PC
 */
public class AplikasiPerhitunganDiskon extends javax.swing.JFrame {
// Fungsi untuk menghitung diskon

// Fungsi untuk menghitung diskon
    private void hitungDiskon() {
        try {
            // Ambil harga input
            String inputHarga = txtInput.getText().trim();
            if (inputHarga.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Masukkan harga terlebih dahulu!");
                return;
            }

            double hargaInput = Double.parseDouble(inputHarga);
            if (hargaInput < 0) {
                throw new NumberFormatException("Harga tidak bisa negatif.");
            }

            // Ambil diskon dari JComboBox
            int diskon = Integer.parseInt(cbbDiskon.getSelectedItem().toString());

            // Cek kode kupon
            String kodeKupon = txtKodeKupon.getText().trim();
            int tambahanDiskon = 0;
            if (kodeKupon.equalsIgnoreCase("DISKON10")) {
                tambahanDiskon = 10;
            } else if (kodeKupon.equalsIgnoreCase("DISKON20")) {
                tambahanDiskon = 20;
            }

            // Hitung total diskon (diskon dari combo box + diskon kupon)
            int totalDiskon = diskon + tambahanDiskon;
            if (totalDiskon > 100) {
                totalDiskon = 100; // Batas maksimum diskon 100%
            }
            // Menghitung jumlah hemat
            double jumlahHemat = hargaInput * totalDiskon / 100.0;

            // Menghitung harga akhir setelah diskon
            double hargaAkhir = hargaInput - jumlahHemat;

            // Menampilkan hasil perhitungan di text field
            txtJumlahHemat.setText(String.format("%.2f", jumlahHemat));
            txtAkhir.setText(String.format("%.2f", hargaAkhir));

            // Tambahkan riwayat ke txtRiwayat
            String riwayat = String.format("Harga Awal: %.2f, Diskon: %d%%, Kupon: %s, Jumlah Hemat: %.2f, Harga Akhir: %.2f\n",
                    hargaInput, totalDiskon, kodeKupon.isEmpty() ? "Tidak Ada" : kodeKupon,
                    jumlahHemat, hargaAkhir);
            txtRiwayat.append(riwayat);

        } catch (NumberFormatException e) {
            // Menangani kesalahan jika input harga tidak valid
            javax.swing.JOptionPane.showMessageDialog(null, "Masukkan harga yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form AplikasiPerhitunganDiskon
     */
    public AplikasiPerhitunganDiskon() {
        initComponents();
        // ChangeListener untuk JSlider
        slDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                int sliderValue = slDiskon.getValue();
                String sliderValueString = String.valueOf(sliderValue);

                // Update JComboBox jika nilai JSlider berubah
                if (!sliderValueString.equals(cbbDiskon.getSelectedItem().toString())) {
                    cbbDiskon.setEditable(true);
                    cbbDiskon.setSelectedItem(sliderValueString);
                    cbbDiskon.setEditable(false);

                }
            }
        });

// ItemListener untuk JComboBox
        cbbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    int comboValue = Integer.parseInt(cbbDiskon.getSelectedItem().toString());

                    // Update JSlider jika pilihan JComboBox berubah
                    if (slDiskon.getValue() != comboValue) {
                        slDiskon.setValue(comboValue);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbDiskon = new javax.swing.JComboBox<>();
        txtInput = new javax.swing.JTextField();
        txtAkhir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJumlahHemat = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtKodeKupon = new javax.swing.JTextField();
        slDiskon = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRiwayat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Hitung Diskon", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Input Harga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Harga Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Jumlah Hemat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jLabel3, gridBagConstraints);

        cbbDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20", "25", "30" }));
        cbbDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDiskonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(cbbDiskon, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(txtInput, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(txtAkhir, gridBagConstraints);

        jLabel4.setText("Pilih Diskon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(txtJumlahHemat, gridBagConstraints);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel1.add(btnHitung, gridBagConstraints);

        jLabel5.setText("Masukkan Kode Kupon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtKodeKupon.setPreferredSize(new java.awt.Dimension(75, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        jPanel1.add(txtKodeKupon, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(slDiskon, gridBagConstraints);

        txtRiwayat.setColumns(20);
        txtRiwayat.setRows(5);
        jScrollPane1.setViewportView(txtRiwayat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitungDiskon();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void cbbDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDiskonItemStateChanged
        hitungDiskon();
    }//GEN-LAST:event_cbbDiskonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbbDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider slDiskon;
    private javax.swing.JTextField txtAkhir;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtJumlahHemat;
    private javax.swing.JTextField txtKodeKupon;
    private javax.swing.JTextArea txtRiwayat;
    // End of variables declaration//GEN-END:variables
}
